# Показать список доступных команд
default:
    @just --list

# Генерация Go-кода из Protobuf
gen:
    @echo "⚙️ Generating Proto..."
    # Создаем директорию, если вдруг её нет (хотя код генерируется рядом)
    # --go_opt=paths=source_relative означает, что структура папок будет как в проекте
    protoc --go_out=. --go_opt=paths=source_relative \
           --go-grpc_out=. --go-grpc_opt=paths=source_relative \
           proto/helloworld/helloworld.proto
    @echo "✅ Done."

# Запустить приложение
run:
    go run main.go

# Обновить зависимости
deps:
    go mod tidy
    gomod2nix

# Собрать бинарник через Nix
build:
    nix build .

# Собрать Docker
docker:
    nix build .#docker
    docker load < result

# Линтеры
lint:
    golangci-lint run

clean:
    rm -rf result
    go clean

grcp-curl:
  grpcurl -plaintext -d '{"name": "Developer"}' localhost:50051 helloworld.Greeter/SayHello
