// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: pkg/proto/notification/notification.proto

package notification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	UserId    string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventType string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// Передаем payload как JSON строку, чтобы сохранить гибкость
	// и не типизировать каждое сообщение чата/системы в proto.
	PayloadJson   []byte `protobuf:"bytes,3,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_pkg_proto_notification_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_notification_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_notification_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *SendRequest) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

type SendReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendReply) Reset() {
	*x = SendReply{}
	mi := &file_pkg_proto_notification_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReply) ProtoMessage() {}

func (x *SendReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_notification_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReply.ProtoReflect.Descriptor instead.
func (*SendReply) Descriptor() ([]byte, []int) {
	return file_pkg_proto_notification_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_pkg_proto_notification_notification_proto protoreflect.FileDescriptor

const file_pkg_proto_notification_notification_proto_rawDesc = "" +
	"\n" +
	")pkg/proto/notification/notification.proto\x12\fnotification\"h\n" +
	"\vSendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12!\n" +
	"\fpayload_json\x18\x03 \x01(\fR\vpayloadJson\"%\n" +
	"\tSendReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2S\n" +
	"\x13NotificationService\x12<\n" +
	"\x04Send\x12\x19.notification.SendRequest\x1a\x17.notification.SendReply\"\x00B\x11Z\x0f./;notificationb\x06proto3"

var (
	file_pkg_proto_notification_notification_proto_rawDescOnce sync.Once
	file_pkg_proto_notification_notification_proto_rawDescData []byte
)

func file_pkg_proto_notification_notification_proto_rawDescGZIP() []byte {
	file_pkg_proto_notification_notification_proto_rawDescOnce.Do(func() {
		file_pkg_proto_notification_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_notification_notification_proto_rawDesc), len(file_pkg_proto_notification_notification_proto_rawDesc)))
	})
	return file_pkg_proto_notification_notification_proto_rawDescData
}

var file_pkg_proto_notification_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_notification_notification_proto_goTypes = []any{
	(*SendRequest)(nil), // 0: notification.SendRequest
	(*SendReply)(nil),   // 1: notification.SendReply
}
var file_pkg_proto_notification_notification_proto_depIdxs = []int32{
	0, // 0: notification.NotificationService.Send:input_type -> notification.SendRequest
	1, // 1: notification.NotificationService.Send:output_type -> notification.SendReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_notification_notification_proto_init() }
func file_pkg_proto_notification_notification_proto_init() {
	if File_pkg_proto_notification_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_notification_notification_proto_rawDesc), len(file_pkg_proto_notification_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_notification_notification_proto_goTypes,
		DependencyIndexes: file_pkg_proto_notification_notification_proto_depIdxs,
		MessageInfos:      file_pkg_proto_notification_notification_proto_msgTypes,
	}.Build()
	File_pkg_proto_notification_notification_proto = out.File
	file_pkg_proto_notification_notification_proto_goTypes = nil
	file_pkg_proto_notification_notification_proto_depIdxs = nil
}
